# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/timur/Desktop/StudentGrading

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/timur/Desktop/StudentGrading/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timur/Desktop/StudentGrading/build/CMakeFiles /home/timur/Desktop/StudentGrading/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timur/Desktop/StudentGrading/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named StudentGrading

# Build rule for target.
StudentGrading: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StudentGrading
.PHONY : StudentGrading

# fast build rule for target.
StudentGrading/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/build
.PHONY : StudentGrading/fast

src/Grading.o: src/Grading.cpp.o
.PHONY : src/Grading.o

# target to build an object file
src/Grading.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/Grading.cpp.o
.PHONY : src/Grading.cpp.o

src/Grading.i: src/Grading.cpp.i
.PHONY : src/Grading.i

# target to preprocess a source file
src/Grading.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/Grading.cpp.i
.PHONY : src/Grading.cpp.i

src/Grading.s: src/Grading.cpp.s
.PHONY : src/Grading.s

# target to generate assembly for a file
src/Grading.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/Grading.cpp.s
.PHONY : src/Grading.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/QuickSort.o: src/QuickSort.cpp.o
.PHONY : src/QuickSort.o

# target to build an object file
src/QuickSort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/QuickSort.cpp.o
.PHONY : src/QuickSort.cpp.o

src/QuickSort.i: src/QuickSort.cpp.i
.PHONY : src/QuickSort.i

# target to preprocess a source file
src/QuickSort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/QuickSort.cpp.i
.PHONY : src/QuickSort.cpp.i

src/QuickSort.s: src/QuickSort.cpp.s
.PHONY : src/QuickSort.s

# target to generate assembly for a file
src/QuickSort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/QuickSort.cpp.s
.PHONY : src/QuickSort.cpp.s

src/Student.o: src/Student.cpp.o
.PHONY : src/Student.o

# target to build an object file
src/Student.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/Student.cpp.o
.PHONY : src/Student.cpp.o

src/Student.i: src/Student.cpp.i
.PHONY : src/Student.i

# target to preprocess a source file
src/Student.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/Student.cpp.i
.PHONY : src/Student.cpp.i

src/Student.s: src/Student.cpp.s
.PHONY : src/Student.s

# target to generate assembly for a file
src/Student.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentGrading.dir/build.make CMakeFiles/StudentGrading.dir/src/Student.cpp.s
.PHONY : src/Student.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... StudentGrading"
	@echo "... src/Grading.o"
	@echo "... src/Grading.i"
	@echo "... src/Grading.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/QuickSort.o"
	@echo "... src/QuickSort.i"
	@echo "... src/QuickSort.s"
	@echo "... src/Student.o"
	@echo "... src/Student.i"
	@echo "... src/Student.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

